In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('turbo.csv')
df

          Price  Year Engine    Distance
0    12 700 AZN  2008  1.5 L  384 633 km
1    19 000 AZN  2010  1.8 L  316 656 km
2    13 900 AZN  2008  1.5 L  175 000 km
3    12 800 AZN  2007  1.5 L  210 000 km
4    14 500 AZN  2006  1.5 L  137 000 km
..          ...   ...    ...         ...
987  19 000 AZN  2012  1.8 L  167 000 km
988  10 000 AZN  2007  1.5 L  187 000 km
989  20 000 AZN  2007  1.5 L  150 000 km
990  13 900 AZN  2008  1.5 L  175 000 km
991  12 200 AZN  2008  1.5 L  150 000 km

[992 rows x 4 columns]

In [3]:
df.shape

(992, 4)

In [4]:
df.head()

        Price  Year Engine    Distance
0  12 700 AZN  2008  1.5 L  384 633 km
1  19 000 AZN  2010  1.8 L  316 656 km
2  13 900 AZN  2008  1.5 L  175 000 km
3  12 800 AZN  2007  1.5 L  210 000 km
4  14 500 AZN  2006  1.5 L  137 000 km

In [5]:
df.head(10)

        Price  Year Engine    Distance
0  12 700 AZN  2008  1.5 L  384 633 km
1  19 000 AZN  2010  1.8 L  316 656 km
2  13 900 AZN  2008  1.5 L  175 000 km
3  12 800 AZN  2007  1.5 L  210 000 km
4  14 500 AZN  2006  1.5 L  137 000 km
5  14 500 AZN  2011  1.8 L  140 000 km
6  12 900 AZN  2008  1.5 L  237 000 km
7  13 100 AZN  2007  1.5 L  195 300 km
8  10 900 AZN  2007  1.5 L  239 000 km
9  12 200 AZN  2008  1.5 L  330 000 km

In [6]:
df.tail()

          Price  Year Engine    Distance
987  19 000 AZN  2012  1.8 L  167 000 km
988  10 000 AZN  2007  1.5 L  187 000 km
989  20 000 AZN  2007  1.5 L  150 000 km
990  13 900 AZN  2008  1.5 L  175 000 km
991  12 200 AZN  2008  1.5 L  150 000 km

In [7]:
df.tail(10)

          Price  Year Engine    Distance
982  13 500 AZN  2008  1.5 L  235 000 km
983  11 000 AZN  2008  1.5 L  222 222 km
984  12 600 AZN  2007  1.5 L  286 463 km
985  14 000 AZN  2007  1.5 L  185 000 km
986  16 700 AZN  2011  1.8 L  160 000 km
987  19 000 AZN  2012  1.8 L  167 000 km
988  10 000 AZN  2007  1.5 L  187 000 km
989  20 000 AZN  2007  1.5 L  150 000 km
990  13 900 AZN  2008  1.5 L  175 000 km
991  12 200 AZN  2008  1.5 L  150 000 km

In [13]:
pd.options.display.max_rows

100

In [14]:
df.head(70)

         Price  Year Engine    Distance
0   12 700 AZN  2008  1.5 L  384 633 km
1   19 000 AZN  2010  1.8 L  316 656 km
2   13 900 AZN  2008  1.5 L  175 000 km
3   12 800 AZN  2007  1.5 L  210 000 km
4   14 500 AZN  2006  1.5 L  137 000 km
5   14 500 AZN  2011  1.8 L  140 000 km
6   12 900 AZN  2008  1.5 L  237 000 km
7   13 100 AZN  2007  1.5 L  195 300 km
8   10 900 AZN  2007  1.5 L  239 000 km
9   12 200 AZN  2008  1.5 L  330 000 km
10  13 500 AZN  2008  1.5 L  210 000 km
11  18 200 AZN  2010  1.8 L  115 000 km
12  13 300 AZN  2008  1.5 L  127 000 km
13  13 800 AZN  2007  1.5 L  191 000 km
14  12 400 AZN  2007  1.5 L  257 000 km
15  13 800 AZN  2007  1.5 L  242 000 km
16  14 100 AZN  2009  1.5 L  219 000 km
17  12 900 AZN  2009  1.5 L  182 300 km
18  13 500 AZN  2009  1.5 L  203 000 km
19  19 800 AZN  2012  1.8 L  190 466 km
20  13 300 AZN  2007  1.5 L  140 000 km
21  18 700 AZN  2012  1.8 L  199 000 km
22  13 200 AZN  2006  1.5 L  169 000 km
23  18 300 AZN  2011  1.8 L  234 000 km
24  18 900 AZN  2011  1.8 L  209 228 km
25  12 800 AZN  2007  1.5 L  255 000 km
26  19 000 AZN  2010  1.8 L  316 656 km
27  15 900 AZN  2009  1.8 L  182 000 km
28  13 200 AZN  2008  1.5 L  392 680 km
29  13 800 AZN  2008  1.5 L  188 000 km
30  13 300 AZN  2007  1.5 L  224 258 km
31  12 950 AZN  2005  1.5 L  202 900 km
32  15 400 AZN  2010  1.8 L  236 574 km
33  10 000 AZN  2007  1.5 L  180 000 km
34  16 300 AZN  2009  1.8 L  150 000 km
35  20 800 AZN  2014  1.8 L  191 587 km
36  13 700 AZN  2008  1.5 L  299 338 km
37  13 500 AZN  2007  1.5 L  233 000 km
38  13 700 AZN  2007  1.5 L  209 000 km
39   9 000 AZN  2009  1.5 L  133 000 km
40  13 900 AZN  2005  1.5 L  150 000 km
41  16 300 AZN  2010  1.8 L  159 000 km
42  10 000 AZN  2007  1.5 L  210 000 km
43  10 500 AZN  2007  1.5 L  185 000 km
44  12 500 AZN  2007  1.5 L  259 700 km
45  14 000 AZN  2008  1.5 L  234 128 km
46  16 500 AZN  2010  1.8 L  183 000 km
47  13 900 AZN  2007  1.5 L  155 621 km
48  13 900 AZN  2008  1.5 L  346 460 km
49  17 400 AZN  2010  1.8 L  202 000 km
50  18 300 AZN  2011  1.8 L  193 121 km
51  13 200 AZN  2008  1.5 L  259 394 km
52  14 800 AZN  2008  1.5 L  211 000 km
53  16 300 AZN  2009  1.8 L  184 800 km
54  14 400 AZN  2008  1.5 L  184 000 km
55  12 900 AZN  2008  1.5 L  244 914 km
56   6 000 AZN  2007  1.5 L  185 000 km
57  20 500 AZN  2013  1.8 L  132 000 km
58  13 800 AZN  2008  1.5 L  225 326 km
59  16 700 AZN  2011  1.8 L  171 000 km
60  17 300 AZN  2011  1.8 L  191 000 km
61  13 700 AZN  2008  1.5 L  197 000 km
62   9 500 AZN  2007  1.5 L  200 000 km
63  16 750 AZN  2011  1.8 L  174 700 km
64  18 500 AZN  2011  1.8 L  190 000 km
65  13 500 AZN  2007  1.5 L  233 000 km
66  17 900 AZN  2011  1.8 L  214 000 km
67  13 300 AZN  2008  1.5 L  200 000 km
68  19 900 AZN  2014  1.8 L  220 000 km
69  19 400 AZN  2013  1.8 L  212 700 km

In [15]:
df.head(110)

          Price  Year Engine    Distance
0    12 700 AZN  2008  1.5 L  384 633 km
1    19 000 AZN  2010  1.8 L  316 656 km
2    13 900 AZN  2008  1.5 L  175 000 km
3    12 800 AZN  2007  1.5 L  210 000 km
4    14 500 AZN  2006  1.5 L  137 000 km
..          ...   ...    ...         ...
105  21 400 AZN  2012  1.8 L  149 050 km
106  13 400 AZN  2007  1.5 L  188 000 km
107  13 400 AZN  2007  1.5 L  210 000 km
108  13 500 AZN  2008  1.5 L  337 962 km
109  15 900 AZN  2011  1.8 L  131 000 km

[110 rows x 4 columns]

In [16]:
pd.options.display.max_rows = 120

In [17]:
df.head(110)

          Price  Year Engine    Distance
0    12 700 AZN  2008  1.5 L  384 633 km
1    19 000 AZN  2010  1.8 L  316 656 km
2    13 900 AZN  2008  1.5 L  175 000 km
3    12 800 AZN  2007  1.5 L  210 000 km
4    14 500 AZN  2006  1.5 L  137 000 km
5    14 500 AZN  2011  1.8 L  140 000 km
6    12 900 AZN  2008  1.5 L  237 000 km
7    13 100 AZN  2007  1.5 L  195 300 km
8    10 900 AZN  2007  1.5 L  239 000 km
9    12 200 AZN  2008  1.5 L  330 000 km
10   13 500 AZN  2008  1.5 L  210 000 km
11   18 200 AZN  2010  1.8 L  115 000 km
12   13 300 AZN  2008  1.5 L  127 000 km
13   13 800 AZN  2007  1.5 L  191 000 km
14   12 400 AZN  2007  1.5 L  257 000 km
15   13 800 AZN  2007  1.5 L  242 000 km
16   14 100 AZN  2009  1.5 L  219 000 km
17   12 900 AZN  2009  1.5 L  182 300 km
18   13 500 AZN  2009  1.5 L  203 000 km
19   19 800 AZN  2012  1.8 L  190 466 km
20   13 300 AZN  2007  1.5 L  140 000 km
21   18 700 AZN  2012  1.8 L  199 000 km
22   13 200 AZN  2006  1.5 L  169 000 km
23   18 300 AZN  2011  1.8 L  234 000 km
24   18 900 AZN  2011  1.8 L  209 228 km
25   12 800 AZN  2007  1.5 L  255 000 km
26   19 000 AZN  2010  1.8 L  316 656 km
27   15 900 AZN  2009  1.8 L  182 000 km
28   13 200 AZN  2008  1.5 L  392 680 km
29   13 800 AZN  2008  1.5 L  188 000 km
30   13 300 AZN  2007  1.5 L  224 258 km
31   12 950 AZN  2005  1.5 L  202 900 km
32   15 400 AZN  2010  1.8 L  236 574 km
33   10 000 AZN  2007  1.5 L  180 000 km
34   16 300 AZN  2009  1.8 L  150 000 km
35   20 800 AZN  2014  1.8 L  191 587 km
36   13 700 AZN  2008  1.5 L  299 338 km
37   13 500 AZN  2007  1.5 L  233 000 km
38   13 700 AZN  2007  1.5 L  209 000 km
39    9 000 AZN  2009  1.5 L  133 000 km
40   13 900 AZN  2005  1.5 L  150 000 km
41   16 300 AZN  2010  1.8 L  159 000 km
42   10 000 AZN  2007  1.5 L  210 000 km
43   10 500 AZN  2007  1.5 L  185 000 km
44   12 500 AZN  2007  1.5 L  259 700 km
45   14 000 AZN  2008  1.5 L  234 128 km
46   16 500 AZN  2010  1.8 L  183 000 km
47   13 900 AZN  2007  1.5 L  155 621 km
48   13 900 AZN  2008  1.5 L  346 460 km
49   17 400 AZN  2010  1.8 L  202 000 km
50   18 300 AZN  2011  1.8 L  193 121 km
51   13 200 AZN  2008  1.5 L  259 394 km
52   14 800 AZN  2008  1.5 L  211 000 km
53   16 300 AZN  2009  1.8 L  184 800 km
54   14 400 AZN  2008  1.5 L  184 000 km
55   12 900 AZN  2008  1.5 L  244 914 km
56    6 000 AZN  2007  1.5 L  185 000 km
57   20 500 AZN  2013  1.8 L  132 000 km
58   13 800 AZN  2008  1.5 L  225 326 km
59   16 700 AZN  2011  1.8 L  171 000 km
60   17 300 AZN  2011  1.8 L  191 000 km
61   13 700 AZN  2008  1.5 L  197 000 km
62    9 500 AZN  2007  1.5 L  200 000 km
63   16 750 AZN  2011  1.8 L  174 700 km
64   18 500 AZN  2011  1.8 L  190 000 km
65   13 500 AZN  2007  1.5 L  233 000 km
66   17 900 AZN  2011  1.8 L  214 000 km
67   13 300 AZN  2008  1.5 L  200 000 km
68   19 900 AZN  2014  1.8 L  220 000 km
69   19 400 AZN  2013  1.8 L  212 700 km
70   22 000 AZN  2012  1.8 L  144 940 km
71   10 000 AZN  2008  1.5 L  155 000 km
72   11 700 AZN  2008  1.5 L  140 000 km
73   13 500 AZN  2009  1.5 L  189 000 km
74   17 500 AZN  2010  1.8 L  179 075 km
75   34 000 AZN  2019  1.8 L   65 000 km
76   19 700 AZN  2013  1.8 L  183 273 km
77   13 200 AZN  2008  1.5 L  179 000 km
78   14 200 AZN  2008  1.5 L  126 000 km
79   12 800 AZN  2008  1.5 L  212 433 km
80   13 600 AZN  2006  1.5 L  286 463 km
81   17 650 AZN  2010  1.8 L  300 000 km
82   16 500 AZN  2009  1.8 L  197 000 km
83   13 700 AZN  2007  1.5 L  116 000 km
84   13 200 AZN  2008  1.5 L  337 962 km
85   14 300 AZN  2009  1.5 L  130 000 km
86   13 500 AZN  2007  1.5 L  210 500 km
87   14 600 AZN  2008  1.5 L  179 000 km
88   11 800 AZN  2008  1.5 L  270 000 km
89   14 500 AZN  2006  1.5 L  161 676 km
90   13 500 AZN  2008  1.5 L  216 000 km
91   17 500 AZN  2010  1.8 L  210 000 km
92   14 400 AZN  2007  1.5 L  139 000 km
93   17 500 AZN  2010  1.8 L  132 200 km
94   11 800 AZN  2008  1.5 L  185 000 km
95   13 750 AZN  2008  1.5 L  255 886 km
96   12 800 AZN  2007  1.5 L  210 000 km
97   18 700 AZN  2012  1.8 L  136 000 km
98   13 750 AZN  2007  1.5 L  212 000 km
99   12 800 AZN  2007  1.5 L  264 000 km
100  12 900 AZN  2006  1.5 L  121 000 km
101  13 500 AZN  2007  1.5 L  233 000 km
102  14 000 AZN  2007  1.5 L   80 000 km
103  17 200 AZN  2011  1.8 L  115 000 km
104  13 700 AZN  2007  1.5 L  209 000 km
105  21 400 AZN  2012  1.8 L  149 050 km
106  13 400 AZN  2007  1.5 L  188 000 km
107  13 400 AZN  2007  1.5 L  210 000 km
108  13 500 AZN  2008  1.5 L  337 962 km
109  15 900 AZN  2011  1.8 L  131 000 km