In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')
df

,title,author,date,views,likes,link
0,Climate action needs new frontline leadership,Ozawa Bineshi Albert,December 2021,404000,12000,https://ted.com/talks/ozawa_bineshi_albert_cli...
1,The dark history of the overthrow of Hawaii,Sydney Iaukea,February 2022,214000,6400,https://ted.com/talks/sydney_iaukea_the_dark_h...
2,How play can spark new ideas for your business,Martin Reeves,September 2021,412000,12000,https://ted.com/talks/martin_reeves_how_play_c...
3,Why is China appointing judges to combat clima...,James K. Thornton,October 2021,427000,12000,https://ted.com/talks/james_k_thornton_why_is_...
4,Cement's carbon problem — and 2 ways to fix it,Mahendra Singhi,October 2021,2400,72,https://ted.com/talks/mahendra_singhi_cement_s...
...,...,...,...,...,...,...
5435,The best stats you've ever seen,Hans Rosling,February 2006,15000000,458000,https://ted.com/talks/hans_rosling_the_best_st...
5436,Do schools kill creativity?,Sir Ken Robinson,February 2006,72000000,2100000,https://ted.com/talks/sir_ken_robinson_do_scho...
5437,Greening the ghetto,Majora Carter,February 2006,2900000,88000,https://ted.com/talks/majora_carter_greening_t...
5438,Simplicity sells,David Pogue,February 2006,2000000,60000,https://ted.com/talks/david_pogue_simplicity_s...
5439,Averting the climate crisis,Al Gore,February 2006,3600000,109000,https://ted.com/talks/al_gore_averting_the_cli...

In [3]:
df.columns

Index(['title', 'author', 'date', 'views', 'likes', 'link'], dtype='object')

In [4]:
df.columns = ['Title', 'Author', 'Date', 'Views', 'Likes', 'Link']
df

,Title,Author,Date,Views,Likes,Link
0,Climate action needs new frontline leadership,Ozawa Bineshi Albert,December 2021,404000,12000,https://ted.com/talks/ozawa_bineshi_albert_cli...
1,The dark history of the overthrow of Hawaii,Sydney Iaukea,February 2022,214000,6400,https://ted.com/talks/sydney_iaukea_the_dark_h...
2,How play can spark new ideas for your business,Martin Reeves,September 2021,412000,12000,https://ted.com/talks/martin_reeves_how_play_c...
3,Why is China appointing judges to combat clima...,James K. Thornton,October 2021,427000,12000,https://ted.com/talks/james_k_thornton_why_is_...
4,Cement's carbon problem — and 2 ways to fix it,Mahendra Singhi,October 2021,2400,72,https://ted.com/talks/mahendra_singhi_cement_s...
...,...,...,...,...,...,...
5435,The best stats you've ever seen,Hans Rosling,February 2006,15000000,458000,https://ted.com/talks/hans_rosling_the_best_st...
5436,Do schools kill creativity?,Sir Ken Robinson,February 2006,72000000,2100000,https://ted.com/talks/sir_ken_robinson_do_scho...
5437,Greening the ghetto,Majora Carter,February 2006,2900000,88000,https://ted.com/talks/majora_carter_greening_t...
5438,Simplicity sells,David Pogue,February 2006,2000000,60000,https://ted.com/talks/david_pogue_simplicity_s...
5439,Averting the climate crisis,Al Gore,February 2006,3600000,109000,https://ted.com/talks/al_gore_averting_the_cli...

In [5]:
df.columns = df.columns.str.replace('e', 'E')

In [6]:
df

,TitlE,Author,DatE,ViEws,LikEs,Link
0,Climate action needs new frontline leadership,Ozawa Bineshi Albert,December 2021,404000,12000,https://ted.com/talks/ozawa_bineshi_albert_cli...
1,The dark history of the overthrow of Hawaii,Sydney Iaukea,February 2022,214000,6400,https://ted.com/talks/sydney_iaukea_the_dark_h...
2,How play can spark new ideas for your business,Martin Reeves,September 2021,412000,12000,https://ted.com/talks/martin_reeves_how_play_c...
3,Why is China appointing judges to combat clima...,James K. Thornton,October 2021,427000,12000,https://ted.com/talks/james_k_thornton_why_is_...
4,Cement's carbon problem — and 2 ways to fix it,Mahendra Singhi,October 2021,2400,72,https://ted.com/talks/mahendra_singhi_cement_s...
...,...,...,...,...,...,...
5435,The best stats you've ever seen,Hans Rosling,February 2006,15000000,458000,https://ted.com/talks/hans_rosling_the_best_st...
5436,Do schools kill creativity?,Sir Ken Robinson,February 2006,72000000,2100000,https://ted.com/talks/sir_ken_robinson_do_scho...
5437,Greening the ghetto,Majora Carter,February 2006,2900000,88000,https://ted.com/talks/majora_carter_greening_t...
5438,Simplicity sells,David Pogue,February 2006,2000000,60000,https://ted.com/talks/david_pogue_simplicity_s...
5439,Averting the climate crisis,Al Gore,February 2006,3600000,109000,https://ted.com/talks/al_gore_averting_the_cli...

In [7]:
df.columns = ['Title', 'Author', 'Date']
df

ValueError: Length mismatch: Expected axis has 6 elements, new values have 3 elements

In [8]:
df.rename(columns = {'TitlE': 'Başlıq', 'LikEs': 'Bəyənmələr'})

,Başlıq,Author,DatE,ViEws,Bəyənmələr,Link
0,Climate action needs new frontline leadership,Ozawa Bineshi Albert,December 2021,404000,12000,https://ted.com/talks/ozawa_bineshi_albert_cli...
1,The dark history of the overthrow of Hawaii,Sydney Iaukea,February 2022,214000,6400,https://ted.com/talks/sydney_iaukea_the_dark_h...
2,How play can spark new ideas for your business,Martin Reeves,September 2021,412000,12000,https://ted.com/talks/martin_reeves_how_play_c...
3,Why is China appointing judges to combat clima...,James K. Thornton,October 2021,427000,12000,https://ted.com/talks/james_k_thornton_why_is_...
4,Cement's carbon problem — and 2 ways to fix it,Mahendra Singhi,October 2021,2400,72,https://ted.com/talks/mahendra_singhi_cement_s...
...,...,...,...,...,...,...
5435,The best stats you've ever seen,Hans Rosling,February 2006,15000000,458000,https://ted.com/talks/hans_rosling_the_best_st...
5436,Do schools kill creativity?,Sir Ken Robinson,February 2006,72000000,2100000,https://ted.com/talks/sir_ken_robinson_do_scho...
5437,Greening the ghetto,Majora Carter,February 2006,2900000,88000,https://ted.com/talks/majora_carter_greening_t...
5438,Simplicity sells,David Pogue,February 2006,2000000,60000,https://ted.com/talks/david_pogue_simplicity_s...
5439,Averting the climate crisis,Al Gore,February 2006,3600000,109000,https://ted.com/talks/al_gore_averting_the_cli...

In [9]:
df.loc[0] = ['Test title', 'Test Author', 'January 2020', 250000, 25000, 'Test URL']

In [10]:
df

,TitlE,Author,DatE,ViEws,LikEs,Link
0,Test title,Test Author,January 2020,250000,25000,Test URL
1,The dark history of the overthrow of Hawaii,Sydney Iaukea,February 2022,214000,6400,https://ted.com/talks/sydney_iaukea_the_dark_h...
2,How play can spark new ideas for your business,Martin Reeves,September 2021,412000,12000,https://ted.com/talks/martin_reeves_how_play_c...
3,Why is China appointing judges to combat clima...,James K. Thornton,October 2021,427000,12000,https://ted.com/talks/james_k_thornton_why_is_...
4,Cement's carbon problem — and 2 ways to fix it,Mahendra Singhi,October 2021,2400,72,https://ted.com/talks/mahendra_singhi_cement_s...
...,...,...,...,...,...,...
5435,The best stats you've ever seen,Hans Rosling,February 2006,15000000,458000,https://ted.com/talks/hans_rosling_the_best_st...
5436,Do schools kill creativity?,Sir Ken Robinson,February 2006,72000000,2100000,https://ted.com/talks/sir_ken_robinson_do_scho...
5437,Greening the ghetto,Majora Carter,February 2006,2900000,88000,https://ted.com/talks/majora_carter_greening_t...
5438,Simplicity sells,David Pogue,February 2006,2000000,60000,https://ted.com/talks/david_pogue_simplicity_s...
5439,Averting the climate crisis,Al Gore,February 2006,3600000,109000,https://ted.com/talks/al_gore_averting_the_cli...

In [11]:
df.loc[1, ['Author', 'ViEws']]

Author    Sydney Iaukea
ViEws            214000
Name: 1, dtype: object

In [12]:
df.loc[1, ['Author', 'ViEws']] = ['Tim Berners-Lee', 500000]
df

,TitlE,Author,DatE,ViEws,LikEs,Link
0,Test title,Test Author,January 2020,250000,25000,Test URL
1,The dark history of the overthrow of Hawaii,Tim Berners-Lee,February 2022,500000,6400,https://ted.com/talks/sydney_iaukea_the_dark_h...
2,How play can spark new ideas for your business,Martin Reeves,September 2021,412000,12000,https://ted.com/talks/martin_reeves_how_play_c...
3,Why is China appointing judges to combat clima...,James K. Thornton,October 2021,427000,12000,https://ted.com/talks/james_k_thornton_why_is_...
4,Cement's carbon problem — and 2 ways to fix it,Mahendra Singhi,October 2021,2400,72,https://ted.com/talks/mahendra_singhi_cement_s...
...,...,...,...,...,...,...
5435,The best stats you've ever seen,Hans Rosling,February 2006,15000000,458000,https://ted.com/talks/hans_rosling_the_best_st...
5436,Do schools kill creativity?,Sir Ken Robinson,February 2006,72000000,2100000,https://ted.com/talks/sir_ken_robinson_do_scho...
5437,Greening the ghetto,Majora Carter,February 2006,2900000,88000,https://ted.com/talks/majora_carter_greening_t...
5438,Simplicity sells,David Pogue,February 2006,2000000,60000,https://ted.com/talks/david_pogue_simplicity_s...
5439,Averting the climate crisis,Al Gore,February 2006,3600000,109000,https://ted.com/talks/al_gore_averting_the_cli...

In [29]:
df['Author'] = df['Author'].str.replace(' ', '_')
df

,TitlE,Author,DatE,ViEws,LikEs,Link
0,Test title,Test_Author,January 2020,250000,25000,Test URL
1,The dark history of the overthrow of Hawaii,Tim_Berners-Lee,February 2022,500000,6400,https://ted.com/talks/sydney_iaukea_the_dark_h...
2,How play can spark new ideas for your business,Martin_Reeves,September 2021,412000,12000,https://ted.com/talks/martin_reeves_how_play_c...
3,Why is China appointing judges to combat clima...,James_K._Thornton,October 2021,427000,12000,https://ted.com/talks/james_k_thornton_why_is_...
4,Cement's carbon problem — and 2 ways to fix it,Mahendra_Singhi,October 2021,2400,72,https://ted.com/talks/mahendra_singhi_cement_s...
...,...,...,...,...,...,...
5435,The best stats you've ever seen,Hans_Rosling,February 2006,15000000,458000,https://ted.com/talks/hans_rosling_the_best_st...
5436,Do schools kill creativity?,Sir_Ken_Robinson,February 2006,72000000,2100000,https://ted.com/talks/sir_ken_robinson_do_scho...
5437,Greening the ghetto,Majora_Carter,February 2006,2900000,88000,https://ted.com/talks/majora_carter_greening_t...
5438,Simplicity sells,David_Pogue,February 2006,2000000,60000,https://ted.com/talks/david_pogue_simplicity_s...
5439,Averting the climate crisis,Al_Gore,February 2006,3600000,109000,https://ted.com/talks/al_gore_averting_the_cli...

In [30]:
def artir(deyer):
    return deyer + 1

In [31]:
df['ViEws'] = df['ViEws'].apply(artir)
df

,TitlE,Author,DatE,ViEws,LikEs,Link
0,Test title,Test_Author,January 2020,250001,25000,Test URL
1,The dark history of the overthrow of Hawaii,Tim_Berners-Lee,February 2022,500001,6400,https://ted.com/talks/sydney_iaukea_the_dark_h...
2,How play can spark new ideas for your business,Martin_Reeves,September 2021,412001,12000,https://ted.com/talks/martin_reeves_how_play_c...
3,Why is China appointing judges to combat clima...,James_K._Thornton,October 2021,427001,12000,https://ted.com/talks/james_k_thornton_why_is_...
4,Cement's carbon problem — and 2 ways to fix it,Mahendra_Singhi,October 2021,2401,72,https://ted.com/talks/mahendra_singhi_cement_s...
...,...,...,...,...,...,...
5435,The best stats you've ever seen,Hans_Rosling,February 2006,15000001,458000,https://ted.com/talks/hans_rosling_the_best_st...
5436,Do schools kill creativity?,Sir_Ken_Robinson,February 2006,72000001,2100000,https://ted.com/talks/sir_ken_robinson_do_scho...
5437,Greening the ghetto,Majora_Carter,February 2006,2900001,88000,https://ted.com/talks/majora_carter_greening_t...
5438,Simplicity sells,David_Pogue,February 2006,2000001,60000,https://ted.com/talks/david_pogue_simplicity_s...
5439,Averting the climate crisis,Al_Gore,February 2006,3600001,109000,https://ted.com/talks/al_gore_averting_the_cli...

In [32]:
df['ViEws'] = df['ViEws'].apply(lambda x: x - 1)
df

,TitlE,Author,DatE,ViEws,LikEs,Link
0,Test title,Test_Author,January 2020,250000,25000,Test URL
1,The dark history of the overthrow of Hawaii,Tim_Berners-Lee,February 2022,500000,6400,https://ted.com/talks/sydney_iaukea_the_dark_h...
2,How play can spark new ideas for your business,Martin_Reeves,September 2021,412000,12000,https://ted.com/talks/martin_reeves_how_play_c...
3,Why is China appointing judges to combat clima...,James_K._Thornton,October 2021,427000,12000,https://ted.com/talks/james_k_thornton_why_is_...
4,Cement's carbon problem — and 2 ways to fix it,Mahendra_Singhi,October 2021,2400,72,https://ted.com/talks/mahendra_singhi_cement_s...
...,...,...,...,...,...,...
5435,The best stats you've ever seen,Hans_Rosling,February 2006,15000000,458000,https://ted.com/talks/hans_rosling_the_best_st...
5436,Do schools kill creativity?,Sir_Ken_Robinson,February 2006,72000000,2100000,https://ted.com/talks/sir_ken_robinson_do_scho...
5437,Greening the ghetto,Majora_Carter,February 2006,2900000,88000,https://ted.com/talks/majora_carter_greening_t...
5438,Simplicity sells,David_Pogue,February 2006,2000000,60000,https://ted.com/talks/david_pogue_simplicity_s...
5439,Averting the climate crisis,Al_Gore,February 2006,3600000,109000,https://ted.com/talks/al_gore_averting_the_cli...

In [33]:
df.apply(len)

TitlE     5440
Author    5440
DatE      5440
ViEws     5440
LikEs     5440
Link      5440
dtype: int64

In [49]:
df[['Link']] = df[['Link']].applymap(len)
df

      TitlE             Author            DatE     ViEws    LikEs  Link
0        10        Test_Author    January 2020    250000    25000     8
1        43    Tim_Berners-Lee   February 2022    500000     6400    79
2        46      Martin_Reeves  September 2021    412000    12000    82
3        56  James_K._Thornton    October 2021    427000    12000    94
4        46    Mahendra_Singhi    October 2021      2400       72    82
...     ...                ...             ...       ...      ...   ...
5435     31       Hans_Rosling   February 2006  15000000   458000    66
5436     27   Sir_Ken_Robinson   February 2006  72000000  2100000    65
5437     19      Majora_Carter   February 2006   2900000    88000    55
5438     16        David_Pogue   February 2006   2000000    60000    50
5439     27            Al_Gore   February 2006   3600000   109000    57

[5440 rows x 6 columns]

In [46]:
df['Author']

0             Test_Author
1         Tim_Berners-Lee
2           Martin_Reeves
3       James_K._Thornton
4         Mahendra_Singhi
              ...
5435         Hans_Rosling
5436     Sir_Ken_Robinson
5437        Majora_Carter
5438          David_Pogue
5439              Al_Gore
Name: Author, Length: 5440, dtype: object